### ISSUE TITLE
 A question about getting data

### ISSUE THREAD

**Issue by KehanChen510** [yashlala/attentive-session-based-recs#2]
hello. When I use _get_file_sh_ in  /data , I get no response when executing line 6, which is _"wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download?id=12FzoWXV65TeUqqs_drCJKaO1Xax0YYTs' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=12FzoWXV65TeUqqs_drCJKaO1Xax0YYTs" -O movies-1m.csv && rm -rf /tmp/cookies.txt" ._ 
An error occurred when I accessed the link to the web page for line 6 command. May I ask if the link to the web page _"https://docs.google.com/uc?export=download?id=12FzoWXV65TeUqqs_drCJKaO1Xax0YYTs"_ is broken? Thank you.

**Comment by yashlala** [comment]
Good question. I remember we updated the links to the google drive (see the latest commit + the README) -- maybe this script hasn't been updated to match. In that case, you'd be able to get the data by using those links manually. 

Let me look into this tomorrow.

**Comment by yashlala** [comment]
@Tchenkovsky I've updated the Google Drive links and fixed the script. 

Please let me know if you run into any other issues.
